### ISSUE TITLE
[FE] 프로젝트 초기 개발 환경 셋팅

### ISSUE THREAD

**Issue by SSUK-H** [Rainbow-SSAP/SSAP-GaNeung#1]
## 작업 사항

> 프로젝트 초기 개발 환경 셋팅을 위해 eslint, prettier 등 설정과 필요한 라이브러리 설치를 진행하였습니다. 그리고 초기 디렉토리 구조 기반으로 프로젝트 개발을 진행할 예정입니다.

## To-do
- [x] CRA, typescript 설치 
- [x] eslint, prettier, stylelint 설치 및 설정
- [x] husky 설치 및 설정
- [x] axios, recoil, react-query, react-router-dom, react-icons, react-hook-form, styled-components, storybook, msw 설치
- [x] 글로벌 스타일, 테마 적용

- 프로젝트의 초기 디렉토리 구조를 설정
    추가된 폴더:
  - `apis`: API 요청과 관련된 로직을 담당합니다.
  - `assets`: 이미지, 폰트 등의 정적 자원을 저장합니다.
  - `components`: 재사용 가능한 UI 컴포넌트를 정의합니다.
  - `constants`: 고정된 값들을 저장합니다.
  - `context`: React Context API를 사용한 상태 관리 로직을 포함합니다.
  - `hooks`: 커스텀 훅을 정의합니다.
  - `mocks`: 테스트나 개발 시 사용할 목 데이터를 저장합니다.
  - `pages`: 각 페이지 컴포넌트를 정의합니다.
  - `router`: 라우팅 관련 로직과 컴포넌트를 포함합니다.
  - `styles`: 전역 스타일과 테마 관련 설정을 담습니다.
  - `types`: TypeScript 타입 정의를 포함합니다.

## 기타사항

>
